spring:
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5432/smartpos_order}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:smartpos}
    password: ${POSTGRES_PASSWORD:smartpos}
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
