server:
  port: 8085

spring:
  application:
    name: AI-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

gemini:
  api:
    key: ${GEMINI_API_KEY:free-stub-key}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
